### ISSUE TITLE
Run the App fails

### ISSUE THREAD

**Issue by Kadantte** [rayriffy/rayriffy-h#618]
```shell
$ now logs https://rayriffy-h-5ytw7cyqp.now.sh
Now CLI 17.0.3
> Fetched deployment "rayriffy-h-5ytw7cyqp.now.sh" in jaejin [1s]
2020-02-16T06:08:50.943Z
2020-02-16T06:08:51.111Z  info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linux-x64.tar.gz
2020-02-16T06:08:54.130Z
2020-02-16T06:08:54.130Z  > core-js@2.6.11 postinstall /zeit/167fe4e4/node_modules/core-js
2020-02-16T06:08:54.130Z  > node -e "try{require('./postinstall')}catch(e){}"
2020-02-16T06:08:54.130Z
2020-02-16T06:08:54.187Z  Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
2020-02-16T06:08:54.187Z
2020-02-16T06:08:54.187Z  The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
2020-02-16T06:08:54.187Z  > https://opencollective.com/core-js
2020-02-16T06:08:54.187Z  > https://www.patreon.com/zloirock
2020-02-16T06:08:54.187Z
2020-02-16T06:08:54.187Z  Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
2020-02-16T06:08:54.187Z
2020-02-16T06:08:54.399Z
2020-02-16T06:08:54.399Z  > core-js@3.6.4 postinstall /zeit/167fe4e4/node_modules/log-process-errors/node_modules/core-js
2020-02-16T06:08:54.399Z  > node -e "try{require('./postinstall')}catch(e){}"
2020-02-16T06:08:54.399Z
2020-02-16T06:08:54.948Z
2020-02-16T06:08:54.948Z  > gatsby-telemetry@1.1.49 postinstall /zeit/167fe4e4/node_modules/gatsby-telemetry
2020-02-16T06:08:54.948Z  > node src/postinstall.js || true
2020-02-16T06:08:54.948Z
2020-02-16T06:08:55.074Z  ╔════════════════════════════════════════════════════════════════════════╗
2020-02-16T06:08:55.075Z  ║                                                                        ║
2020-02-16T06:08:55.075Z  ║   Gatsby collects anonymous usage analytics                            ║
2020-02-16T06:08:55.075Z  ║   to help improve Gatsby for all users.                                ║
2020-02-16T06:08:55.075Z  ║                                                                        ║
2020-02-16T06:08:55.075Z  ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
2020-02-16T06:08:55.075Z  ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
2020-02-16T06:08:55.075Z  ║                                                                        ║
2020-02-16T06:08:55.075Z  ╚════════════════════════════════════════════════════════════════════════╝
2020-02-16T06:08:55.154Z
2020-02-16T06:08:55.154Z  > gatsby-cli@2.8.29 postinstall /zeit/167fe4e4/node_modules/gatsby/node_modules/gatsby-cli
2020-02-16T06:08:55.154Z  > node scripts/postinstall.js
2020-02-16T06:08:55.154Z
2020-02-16T06:08:55.231Z
2020-02-16T06:08:55.231Z  > gatsby@2.19.17 postinstall /zeit/167fe4e4/node_modules/gatsby
2020-02-16T06:08:55.231Z  > node scripts/postinstall.js
2020-02-16T06:08:55.231Z
2020-02-16T06:08:55.435Z
2020-02-16T06:08:55.435Z  > netlify-cli@2.32.0 postinstall /zeit/167fe4e4/node_modules/netlify-cli
2020-02-16T06:08:55.435Z  > node ./scripts/postinstall.js
2020-02-16T06:08:55.435Z
2020-02-16T06:08:55.500Z
2020-02-16T06:08:55.501Z  Success! Netlify CLI has been installed!
2020-02-16T06:08:55.501Z
2020-02-16T06:08:55.501Z  Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.
2020-02-16T06:08:55.501Z
2020-02-16T06:08:55.501Z  Next steps:
2020-02-16T06:08:55.501Z
2020-02-16T06:08:55.501Z    netlify init     Connect or create a Netlify site from current directory
2020-02-16T06:08:55.501Z    netlify deploy   Deploy the latest changes to your Netlify site
2020-02-16T06:08:55.501Z
2020-02-16T06:08:55.501Z  For more information on the CLI run netlify help
2020-02-16T06:08:55.501Z  Or visit the docs at https://cli.netlify.com
2020-02-16T06:08:55.502Z
2020-02-16T06:08:57.169Z  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
2020-02-16T06:08:57.170Z  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-02-16T06:08:57.170Z  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
2020-02-16T06:08:57.170Z  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-02-16T06:08:57.171Z
2020-02-16T06:08:57.183Z  added 2395 packages from 991 contributors in 34.224s
2020-02-16T06:08:57.256Z  Running "npm run build"
2020-02-16T06:08:57.442Z
2020-02-16T06:08:57.442Z  > rayriffy-h@3.6.0 build /zeit/167fe4e4
2020-02-16T06:08:57.442Z  > gatsby build
2020-02-16T06:08:57.442Z
2020-02-16T06:08:57.630Z  ╔════════════════════════════════════════════════════════════════════════╗
2020-02-16T06:08:57.630Z  ║                                                                        ║
2020-02-16T06:08:57.630Z  ║   Gatsby collects anonymous usage analytics                            ║
2020-02-16T06:08:57.630Z  ║   to help improve Gatsby for all users.                                ║
2020-02-16T06:08:57.630Z  ║                                                                        ║
2020-02-16T06:08:57.630Z  ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
2020-02-16T06:08:57.630Z  ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
2020-02-16T06:08:57.630Z  ║                                                                        ║
2020-02-16T06:08:57.630Z  ╚════════════════════════════════════════════════════════════════════════╝
2020-02-16T06:08:57.905Z  The above error occurred in the <StoreStateProvider> component:
2020-02-16T06:08:57.905Z      in StoreStateProvider
2020-02-16T06:08:57.905Z      in App
2020-02-16T06:08:57.905Z
2020-02-16T06:08:57.905Z  React will try to recreate this component tree from scratch using the error boundary you provided, App.
2020-02-16T06:08:57.907Z  Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
2020-02-16T06:08:59.269Z  npm ERR! code ELIFECYCLE
2020-02-16T06:08:59.269Z  npm ERR! errno 1
2020-02-16T06:08:59.269Z  npm ERR! rayriffy-h@3.6.0 build: `gatsby build`
2020-02-16T06:08:59.270Z  npm ERR! Exit status 1
2020-02-16T06:08:59.270Z  npm ERR!
2020-02-16T06:08:59.270Z  npm ERR! Failed at the rayriffy-h@3.6.0 build script.
2020-02-16T06:08:59.270Z  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-02-16T06:08:59.277Z
2020-02-16T06:08:59.277Z  npm ERR! A complete log of this run can be found in:
2020-02-16T06:08:59.277Z  npm ERR!     /zeit/.npm/_logs/2020-02-16T06_08_59_270Z-debug.log
2020-02-16T06:08:59.288Z  Error: Exited with 1
2020-02-16T06:08:59.288Z      at ChildProcess.<anonymous> (/zeit/72d2a711565ce413/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:33891:24)
2020-02-16T06:08:59.288Z      at ChildProcess.emit (events.js:210:5)
2020-02-16T06:08:59.288Z      at ChildProcess.EventEmitter.emit (domain.js:475:20)
2020-02-16T06:08:59.288Z      at maybeClose (internal/child_process.js:1021:16)
2020-02-16T06:08:59.288Z      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-02-16T06:08:59.401Z  worker exited with code 20 and signal null
2020-02-16T06:09:01.702Z  Done with "package.json"
```

**Comment by rayriffy** [comment]
Hmm...that's not seems right.
My best guess right now is Zeit Now install dependency by using `npm` instead of `yarn`

When `npm` is installing dependencies, it cannot find `package-lock.json` file and decided to fetch dependencies from registry.

But in my `package.json` is having an caret in experimental `react` version. So `npm` resolved and get older version of `react` (`0.0.0-fec00a869` to be exact) instead which does not have [ReactDOM.createRoot()](https://reactjs.org/docs/concurrent-mode-reference.html#createroot) rehydrate function

```
"react": "^0.0.0-experimental-241c4467e",
"react-dom": "^0.0.0-experimental-241c4467e",
```

I just patched with commit ec0cb5061730a7bf4a048f1f4bf2500fc39f6c02 but can you to running deployment again with `yarn` instead of `npm` first and then try this latest commit?

**Comment by rayriffy** [comment]
Here's my log from Zeit with current lastest commit

```
rayriffy at r4yr1ffy in ~/Documents/Git/rayriffy-h on master ✔                                                                        [ec0cb50]  1:51
> now
Now CLI 17.0.3
? Set up and deploy “~/Documents/Git/rayriffy-h”? [Y/n] y
? Which scope do you want to deploy to? Phumrapee Limpianchop
? Link to existing project? [y/N] n
? What’s your project’s name? rayriffy-h
? In which directory is your code located? rayriffy-h/
Auto-detected project settings (Gatsby):
- Build Command: `gatsby build` or `build` from `package.json`
- Output Directory: public
- Development Command: gatsby develop --port $PORT
? Want to override the settings? [y/N] n
🔗  Linked to rayriffy/rayriffy-h (created .now and added it to .gitignore)
🔍  Inspect: https://zeit.co/rayriffy/rayriffy-h/n1q8j1wy1 [2s]
✅  Production: https://rayriffy-h.now.sh [copied to clipboard] [7m]
📝  Deployed to production. Run `now --prod` to overwrite later (https://zeit.ink/2F).
💡  To change the domain or build command, go to https://zeit.co/rayriffy/rayriffy-h/settings
rayriffy at r4yr1ffy in ~                                                                                                                      × 1:57
> now switch rayriffy
Now CLI 17.0.3
> Success! Your account (rayriffy) is now active!
rayriffy at r4yr1ffy in ~                                                                                                                        1:57
> now log rayriffy-h-n1q8j1wy1.now.sh
Now CLI 17.0.3
> Fetched deployment "rayriffy-h-n1q8j1wy1.now.sh" in rayriffy [2s]
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > react-focus-lock > use-sidecar@1.0.2" has incorrect peer dependency "react@^16.8.0".
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > toasted-notes > @reach/alert@0.1.5" has incorrect peer dependency "react@^16.8.0".
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > toasted-notes > @reach/alert@0.1.5" has incorrect peer dependency "react-dom@^16.8.0".
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > use-dark-mode > @use-it/event-listener@0.1.3" has incorrect peer dependency "react@^16.8.0".
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > use-dark-mode > use-persisted-state@0.3.0" has incorrect peer dependency "react@^16.8.0".
2020-02-16T18:53:31.171Z  warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has unmet peer dependency "prop-types@^15.6.2".
2020-02-16T18:53:31.172Z  warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has incorrect peer dependency "react@^16.4.0".
2020-02-16T18:53:31.172Z  warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/component-component@0.1.3" has incorrect peer dependency "react-dom@^16.4.0".
2020-02-16T18:53:31.172Z  warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/visually-hidden@0.1.4" has incorrect peer dependency "react@^16.8.0".
2020-02-16T18:53:31.172Z  warning "@chakra-ui/core > toasted-notes > @reach/alert > @reach/visually-hidden@0.1.4" has incorrect peer dependency "react-dom@^16.8.0".
2020-02-16T18:53:31.172Z  warning " > @emotion/core@10.0.27" has incorrect peer dependency "react@>=16.3.0".
2020-02-16T18:53:31.172Z  warning " > @emotion/styled@10.0.27" has incorrect peer dependency "react@>=16.3.0".
2020-02-16T18:53:31.172Z  warning "@emotion/styled > @emotion/styled-base@10.0.27" has incorrect peer dependency "react@>=16.3.0".
2020-02-16T18:53:31.172Z  warning " > emotion-theming@10.0.27" has incorrect peer dependency "react@>=16.3.0".
2020-02-16T18:53:31.172Z  warning " > gatsby@2.19.17" has incorrect peer dependency "react@^16.4.2".
2020-02-16T18:53:31.173Z  warning " > gatsby@2.19.17" has incorrect peer dependency "react-dom@^16.4.2".
2020-02-16T18:53:31.173Z  warning "gatsby > @reach/router@1.3.1" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
2020-02-16T18:53:31.173Z  warning "gatsby > @reach/router@1.3.1" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
2020-02-16T18:53:31.175Z  warning "gatsby > gatsby-link@2.2.29" has incorrect peer dependency "react@^16.4.2".
2020-02-16T18:53:31.175Z  warning "gatsby > gatsby-link@2.2.29" has incorrect peer dependency "react-dom@^16.4.2".
2020-02-16T18:53:31.175Z  warning "gatsby > gatsby-react-router-scroll@2.1.21" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.175Z  warning "gatsby > gatsby-react-router-scroll@2.1.21" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.176Z  warning "gatsby > react-hot-loader@4.12.19" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.176Z  warning "gatsby > react-hot-loader@4.12.19" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.176Z  warning "gatsby > react-hot-loader@4.12.19" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.176Z  warning "gatsby > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.180Z  warning "gatsby-plugin-emotion > @emotion/babel-preset-css-prop > @babel/plugin-transform-react-jsx@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
2020-02-16T18:53:31.180Z  warning "gatsby-plugin-emotion > @emotion/babel-preset-css-prop > @emotion/babel-plugin-jsx-pragmatic > @babel/plugin-syntax-jsx@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
2020-02-16T18:53:31.181Z  warning " > gatsby-plugin-chakra-ui@0.1.2" has incorrect peer dependency "@chakra-ui/core@0.3.2".
2020-02-16T18:53:31.181Z  warning "gatsby-plugin-emotion > @emotion/babel-preset-css-prop@10.0.27" has unmet peer dependency "@babel/core@^7.0.0".
2020-02-16T18:53:31.181Z  warning "gatsby-plugin-emotion > @emotion/babel-preset-css-prop > @emotion/babel-plugin-jsx-pragmatic@0.1.5" has unmet peer dependency "@babel/core@^7.0.0".
2020-02-16T18:53:31.181Z  warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
2020-02-16T18:53:31.182Z  warning " > react-helmet@5.2.1" has incorrect peer dependency "react@>=15.0.0".
2020-02-16T18:53:31.182Z  warning "react-helmet > react-side-effect@1.2.0" has incorrect peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.182Z  warning " > react-lazyload@2.6.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.183Z  warning " > react-lazyload@2.6.5" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
2020-02-16T18:53:31.183Z  warning " > web-api-hooks@2.2.2" has incorrect peer dependency "react@>=16.8".
2020-02-16T18:53:31.183Z  warning " > workerize-loader@1.1.0" has unmet peer dependency "webpack@*".
2020-02-16T18:53:39.442Z  [4/4] Building fresh packages...
2020-02-16T18:53:43.287Z  Done in 28.68s.
2020-02-16T18:53:43.314Z  Running "yarn run build"
2020-02-16T18:53:43.470Z  yarn run v1.22.0
2020-02-16T18:53:43.509Z  $ gatsby build
2020-02-16T18:53:43.707Z  ╔════════════════════════════════════════════════════════════════════════╗
2020-02-16T18:53:43.707Z  ║                                                                        ║
2020-02-16T18:53:43.707Z  ║   Gatsby collects anonymous usage analytics                            ║
2020-02-16T18:53:43.707Z  ║   to help improve Gatsby for all users.                                ║
2020-02-16T18:53:43.707Z  ║                                                                        ║
2020-02-16T18:53:43.708Z  ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
2020-02-16T18:53:43.708Z  ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
2020-02-16T18:53:43.708Z  ║                                                                        ║
2020-02-16T18:53:43.708Z  ╚════════════════════════════════════════════════════════════════════════╝
2020-02-16T18:53:45.237Z  success open and validate gatsby-configs - 0.030s
2020-02-16T18:53:45.524Z  success load plugins - 0.276s
2020-02-16T18:53:45.542Z  success onPreInit - 0.008s
2020-02-16T18:53:45.559Z  success delete html and css files from previous builds - 0.007s
2020-02-16T18:53:45.575Z  success initialize cache - 0.006s
2020-02-16T18:53:45.604Z  success copy gatsby files - 0.020s
2020-02-16T18:53:45.620Z  success onPreBootstrap - 0.006s
2020-02-16T18:53:45.630Z  success createSchemaCustomization - 0.001s
2020-02-16T18:53:45.713Z  success source and transform nodes - 0.073s
2020-02-16T18:53:45.947Z  success building schema - 0.224s
2020-02-16T18:53:45.961Z  info Downloading prefetched data from GitHub Gist
2020-02-16T18:53:46.301Z  info Downloaded!
2020-02-16T18:54:15.528Z  success createPages - 29.565s
2020-02-16T18:54:15.603Z  success createPagesStatefully - 0.061s
2020-02-16T18:54:15.616Z  success onPreExtractQueries - 0.001s
2020-02-16T18:54:21.482Z  warn There are conflicting field types in your data.
2020-02-16T18:54:21.482Z
2020-02-16T18:54:21.482Z  If you have explicitly defined a type for those fields, you can safely ignore this warning message.
2020-02-16T18:54:21.482Z  Otherwise, Gatsby will omit those fields from the GraphQL schema.
2020-02-16T18:54:21.482Z
2020-02-16T18:54:21.482Z  If you know all field types in advance, the best strategy is to explicitly define them with the
2020-02-16T18:54:21.482Z  `createTypes` action, and skip inference with the `@dontInfer` directive.
2020-02-16T18:54:21.488Z  SitePage.context.raw:
2020-02-16T18:54:21.488Z   - type: array
2020-02-16T18:54:21.488Z     value: [ ..., { status: 'success', data: [Object], id: 2937, name: 'String', type: 'tag' }, ... ]
2020-02-16T18:54:21.488Z   - type: object
2020-02-16T18:54:21.488Z     value: { status: 'success', data: [Object] }
2020-02-16T18:54:21.502Z  success update schema - 5.872s
2020-02-16T18:54:21.614Z  success extract queries from components - 0.091s
2020-02-16T18:54:21.661Z  success write out requires - 0.034s
2020-02-16T18:54:21.676Z  success write out redirect data - 0.002s
2020-02-16T18:54:21.785Z  success Build manifest and related icons - 0.095s
2020-02-16T18:54:21.787Z  info Generating API
2020-02-16T18:54:34.465Z  info API generated
2020-02-16T18:54:34.673Z  success onPostBootstrap - 12.980s
2020-02-16T18:54:34.675Z  ⠀
2020-02-16T18:54:34.677Z  info bootstrap finished - 51.153 s
2020-02-16T18:54:34.678Z  ⠀
2020-02-16T18:55:02.035Z  success Building production JavaScript and CSS bundles - 27.285s
2020-02-16T18:55:02.123Z  success Rewriting compilation hashes - 0.002s
2020-02-16T18:55:04.130Z  success run queries - 29.411s - 3022/3022 102.75/s
2020-02-16T18:55:25.158Z  success Building static HTML for pages - 20.756s - 3022/3022 145.60/s
2020-02-16T18:55:25.335Z  info Generated public/sw.js, which will precache 7 files, totaling 678981 bytes.
2020-02-16T18:55:25.335Z  The following pages will be precached:
2020-02-16T18:55:25.335Z  /offline-plugin-app-shell-fallback/index.html
2020-02-16T18:55:25.371Z  success onPostBuild - 0.177s
2020-02-16T18:55:25.420Z  info Done building in 101.894523371 sec
2020-02-16T18:55:25.620Z  Done in 102.15s.
```

**Comment by Kadantte** [comment]
Ok, first I'll try to run yarn on my Machine then gonna test it on Zeit.

**Comment by Kadantte** [comment]
It works fine now on my machine and on ZEIT too, All thank's to you, thank you again.
